export const eng_krd = {
  account_krd: {
    account: "",
    position: "",
    studnet_stat: "",
    course_stat: "",
    video_stat: "",
    acc_setting: "",
    update_acc: "",
    update_info: "",
    support: "",
    help: "",
    about: "",
    logout: "",
    delete_acc: "",
  },
  account_eng: {
    account: "Account",
    position: "",
    studnet_stat: "",
    course_stat: "",
    video_stat: "",
    acc_setting: "Settings",
    update_acc: "Update Account",
    update_info: "Update Info",
    support: "Support",
    help: "Help",
    about: "About",
    logout: "Log out",
    delete_acc: "Delete Account",
  },
};
