export const eng_krd = {
  account_krd: {
    account: "",
    position: "",
    studnet_stat: "",
    course_stat: "",
    video_stat: "",
    acc_setting: "",
    update_acc: "",
    update_info: "",
    support: "",
    help: "",
    about: "",
    logout: "",
    delete_acc: "",
  },
  account_eng: {
    account: "Account",
    position: "",
    studnet_stat: "",
    course_stat: "",
    video_stat: "",
    acc_setting: "Settings",
    update_acc: "Update Account",
    update_info: "Update Info",
    support: "Support",
    help: "Help",
    about: "About",
    logout: "Log out",
    delete_acc: "Delete Account",
  },
  home_krd: {
    home: "",
    welcome: "",
  },
  home_eng: {
    home: "Home",
    welcome: "Welcome",
  },
  course_video_krd: {
    course: "",
    video: "",
    search: "",
    new_course: "",
    upload: "",
    view: "",
    update: "",
    delete: "",
    view_video: "",
    edit_video: "",
    delete_video: "",
  },
  course_video_eng: {
    course: "Courses",
    video: "Videos",
    search: "Search",
    new_course: "Add Course",
    upload: "Upload",
    view: "View",
    update: "Update",
    delete: "Delete",
    view_view: "View Video",
    edit_video: "Edit Video",
    delete_video: "Delete Video",
  },
};
